default_env: &default
  adapter: postgresql
  encoding: unicode
  # 追加
  pool: 5
  username: postgres
  password: YAMATO2199
  host: localhost
  port: 5433

development:
  <<: *default
  database: pif_development

production:
  <<: *default
  database: pif_production
