Enemyfreet.create(name: "敵1", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Enemyfreet.create(name: "敵2", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Enemyfreet.create(name: "敵3", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Enemyfreet.create(name: "敵4", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Enemyfreet.create(name: "敵5", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Enemyfreet.create(name: "敵6", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Myfreet.create(name: "味方1", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Myfreet.create(name: "味方2", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Myfreet.create(name: "味方3", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Story.create(name: "てすと", episode: "0", text: "1")
Story.create(name: "てすと", episode: "0", text: "2")
Story.create(name: "てすと", episode: "0", text: "3")
Story.create(name: "てすと", episode: "0", text: "4")
Story.create(name: "てすと", episode: "0", text: "5")
Story.create(name: "てすと", episode: "0", text: "6")
Story.create(name: "てすと", episode: "0", text: "7")
Story.create(name: "てすと", episode: "0", text: "8")
Story.create(name: "てすと", episode: "0", text: "9")
Story.create(name: "てすと", episode: "0", text: "10")
Story.create(name: "てすと", episode: "0", text: "11")
Story.create(name: "てすと", episode: "0", text: "12")
Story.create(name: "てすと", episode: "0", text: "13")
Story.create(name: "てすと", episode: "0", text: "14")
Story.create(name: "てすと", episode: "0", text: "15")
Story.create(name: "てすと", episode: "0", text: "16")
Story.create(name: "てすと", episode: "0", text: "17")
