Enemyfreet.create(name: "敵1", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Enemyfreet.create(name: "敵2", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Enemyfreet.create(name: "敵3", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Enemyfreet.create(name: "敵4", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Enemyfreet.create(name: "敵5", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Enemyfreet.create(name: "敵6", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Myfreet.create(name: "味方1", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Myfreet.create(name: "味方2", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Myfreet.create(name: "味方3", hp: "100", max_hp: "100", atk: "25", info: "てんぷれーと")
Story.create(name: "＜紫星・磯秋より、紫星・Userへ、メッセージを送信します。＞", episode: "0", text: "1")
Story.create(name: "「あなたはもう、こちらに向かっているのでしょうか。宇宙船の中、あるいは情報網の中で、あなたはこの星…紫星に向かってくるでしょう。次の紫星は、何を信じ、どこに向かっていくのでしょうか。自分にはそれを見届ける事は出来ない。そしてあなたの返事も、届くことはないのでしょう。それでも、我々は戦い続けなければなりません。何故ならこの星は…」", episode: "0", text: "2")
Story.create(name: "＜時間切れになりました。メッセージを終了します。＞", episode: "0", text: "3")
Story.create(name: "「間もなく、紫星に到着します。準備はよろしいですか？」", episode: "0", text: "4")
Story.create(name: "「紫星に到着しました。」", episode: "0", text: "5")
Story.create(name: "宇宙船のドアが開き、あなたは紫星の大地に降り立ちました。", episode: "0", text: "6")
Story.create(name: "「これが最後と、何度願ったでしょうか。」", episode: "0", text: "7")
Story.create(name: "そんな独り言を残して、宇宙船は再び発進しました。", episode: "0", text: "8")
Story.create(name: "ー紫星ー", episode: "0", text: "9")
Story.create(name: "「君かね、紫星の新しいSQUIDERは。＜変更＞の略である。まぁ、宇宙からの敵など、来るはずがない。楽な役回りと思って、せいぜい楽しみたまえ。…何？過去からのメッセージだと？そんないたずらに向き合う程の暇とは聞いてないぞ。とにかく、正式な手続きはあの建物の中で行われる。詳しい説明は磯秋にでも聞いてくれ。それではこの辺で失礼する。」", episode: "0", text: "10")
Story.create(name: "ーSQUIDER本部ー", episode: "0", text: "11")
Story.create(name: "「ああ、君か。SQUIDERの新しい隊員は。隊長の磯秋だ。今日から君は、新設された「みふさ艦隊」の司令を担当する訳だが、何か質問は…ありそうな顔だな。資料を見てほしい…か。（資料を見る）すまないが、少なくとも「この俺ではない」事は確かだ。とにかく今日は拠点を見て回る日だ。」", episode: "0", text: "12")
Story.create(name: "「今日からあなたの補佐をするロボットです。よろしくお願いいたします。それでは拠点をご案内します。」", episode: "0", text: "13")
Story.create(name: "てすと", episode: "1", text: "14")
Story.create(name: "＜集結編第1話　未知の通信システム＞", episode: "1", text: "15")
Story.create(name: "てすと", episode: "1", text: "16")
Story.create(name: "てすと", episode: "1", text: "17")
